Import the necessary packages

In [1]:
import numpy
import matplotlib.pyplot as plt
from keras.utils import np_utils
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dense, Flatten
from tensorflow.keras.optimizers import Adam

Load data

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [4]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [5]:
y_train[0]

5

Data Preprocessing

In [6]:
X_train = X_train.reshape(60000, 28, 28, 1).astype('float32')
X_test = X_test.reshape(10000, 28, 28, 1).astype('float32')

In [7]:
number_of_classes = 10
Y_train = np_utils.to_categorical(y_train, number_of_classes)
Y_test = np_utils.to_categorical(y_test, number_of_classes)

In [8]:
Y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

Create Model

In [9]:
model = Sequential()
model.add(Conv2D(64, (3, 3), input_shape=(28, 28, 1), activation="relu"))
model.add(Conv2D(32, (3, 3), activation="relu"))
model.add(Flatten())
model.add(Dense(number_of_classes, activation="softmax"))

In [10]:
model.compile(loss='categorical_crossentropy', optimizer="Adam", metrics=["accuracy"])

Train the model

In [11]:
model.fit(X_train, Y_train, batch_size=32, epochs=5, validation_data=(X_test,Y_test))

Epoch 1/5
1875/1875 [==============================] - 190s 101ms/step - loss: 0.2146 - accuracy: 0.9499 - val_loss: 0.0982 - val_accuracy: 0.9707
Epoch 2/5
1875/1875 [==============================] - 187s 100ms/step - loss: 0.0690 - accuracy: 0.9791 - val_loss: 0.0982 - val_accuracy: 0.9702
Epoch 3/5
1875/1875 [==============================] - 188s 100ms/step - loss: 0.0426 - accuracy: 0.9860 - val_loss: 0.0974 - val_accuracy: 0.9732
Epoch 4/5
1875/1875 [==============================] - 188s 100ms/step - loss: 0.0350 - accuracy: 0.9886 - val_loss: 0.0928 - val_accuracy: 0.9787
Epoch 5/5
1875/1875 [==============================] - 187s 100ms/step - loss: 0.0265 - accuracy: 0.9917 - val_loss: 0.1116 - val_accuracy: 0.9760


Test the model

In [12]:
metrics = model.evaluate(X_test, Y_test, verbose=0)
print("Metrics (Test Loss & Test Accuracy): ")
print(metrics)

Metrics (Test Loss & Test Accuracy): 
[0.11160511523485184, 0.9760000109672546]


In [13]:
prediction = model.predict(X_test[:4])
print(prediction)

1/1 [==============================] - 0s 83ms/step
[[1.6173502e-15 1.8331794e-16 3.7556121e-12 3.1653488e-12 4.5284456e-17
  8.0359223e-18 1.2975092e-19 1.0000000e+00 2.9545969e-12 6.6488286e-13]
 [7.5071007e-09 2.3938067e-11 1.0000000e+00 6.0749517e-12 9.5716229e-18
  2.7969047e-18 3.9555115e-09 4.8662676e-18 1.4531439e-08 9.3050381e-16]
 [6.1539371e-11 9.9989796e-01 3.6717418e-07 1.2167331e-12 7.0630718e-05
  2.9492836e-07 3.7706229e-09 4.3242466e-08 3.0694209e-05 2.8426846e-12]
 [1.0000000e+00 1.4209496e-16 5.9510803e-12 3.2594144e-18 5.1353453e-14
  1.6226294e-13 1.3767951e-13 5.2482324e-13 6.5111722e-12 6.3832044e-11]]


In [14]:
print(numpy.argmax(prediction, axis=1))
print(Y_test[:4])

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
